FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# копируем только код, НО НЕ credentials.json
COPY app.py .

CMD ["python3", "app.py"]

